// import localFont from "next/font/local";
// import { ServerStylesheet } from "styled-components";
// import { Fragment } from "react";
// import Header from "./components/header/navbar/page";
// import Footer from "./components/footer/page";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable}`}
//         style={{
//           display: "flex",
//           flexDirection: "column",
//           minHeight: "100vh",
//         }}
//       >
//         <Fragment>{sheet.collectStyles(children)}</Fragment>
//         {shet.getStyleElement()}
//         <Header />
//         <main>{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }


// app/layout.js

// "use client" direktivasini olib tashlaymiz, chunki bu server component
import localFont from "next/font/local";
import { Fragment } from "react";
import Header from "./components/header/navbar/page"; // Client component
import Footer from "./components/footer/page"; // Client component

// metadata faqat serverda bo'ladi
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Server componentni yaratamiz
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
        }}
      >
        <Fragment>{children}</Fragment>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
