// import "./globals.css";
import Header from "./components/header/navbar/page"; // Client component
import Footer from "./components/footer/page"; // Client component

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
          margin: "0",
          padding: "0",
          width: "100%",
          overflowX: "hidden",
        }}
      >
        {/* <Header /> */}
        <main
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh",
          }}
        >
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
